name: build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        version:
            - "StableFullRelease"
            - "StableFdroidRelease"
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: ./gradlew build${{ matrix.version }} && ./gradlew clean
